sudo: required
language: generic

services:
  - docker

before_install:
  - docker build --tag rc6886/docker-react --file Dockerfile.dev .

script:
  - docker run -e CI=true rc6886/docker-react npm run test
